CREATE TABLE "users"."accounts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT
        NOT NULL
        CONSTRAINT "users.accounts-logic-uniqueUsernames" UNIQUE
        CONSTRAINT "users.accounts-logic-lengthUsername" CHECK (length("username") > 3),
    "password" TEXT
        NOT NULL
        CONSTRAINT "users.accounts-system-validBCryptHashOnPassword"
            CHECK ("password" ~ '^\$2[ayb]\$.{56}$'),
    "created" TIMESTAMP WITHOUT TIME ZONE
        NOT NULL
        DEFAULT TIMEZONE('UTC', now()),
);

-- User for system messages
INSERT INTO
    "users"."accounts" ("id", "username", "password", "created")
VALUES
    (0, 'system', 'password', '2023-09-01 11:00:00'::TIMESTAMP WITHOUT TIME ZONE);

CREATE TABLE "users"."profiles" (
    "user-id" BIGINT
        NOT NULL,
    "version" SMALLINT
        NOT NULL,
    "nickname" TEXT
        CONSTRAINT "users.profiles-logic-notEmptyNickname" CHECK (length("username") > 0),
    "avatar-id" BIGINT,
    "description" TEXT,
    PRIMARY KEY ("user-id", "version")
    CONSTRAINT "users.profiles-FK-userID" FOREIGN KEY ("user-id") REFERENCES "users"."accounts" ("id")
);

CREATE TABLE "users"."tokens" (
    "user-id" BIGINT
        NOT NULL,
    "first" TEXT
        NOT NULL,
    "second" TEXT
        NOT NULL,
    "created-at" TIMESTAMP WITHOUT TIME ZONE
        NOT NULL,
    "user-agent" TEXT
        NOT NULL,
    CONSTRAINT "users.tokens-FK-userID" FOREIGN KEY ("user-id") REFERENCES "users"."accounts" ("id"),
    CONSTRAINT "users.tokens-system-validBCryptHashOnTokenParts"
        CHECK (("first" ~ '^\$2[ayb]\$.{56}$') AND ("second" ~ '^\$2[ayb]\$.{56}$')),
);
