CREATE TABLE users.accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL CHECK (length(username) > 3),
    password TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users.confirmations (
    client BIGINT PRIMARY KEY,
    confirmation SMALLINT NOT NULL DEFAULT 0,
    email TEXT UNIQUE,
    emails TEXT[],
    phone TEXT UNIQUE,
    FOREIGN KEY (client) REFERENCES users.accounts (id)
);

CREATE TABLE users.accounts_changes (
    client BIGINT PRIMARY KEY,
    username TIMESTAMP[],
    password TIMESTAMP[],
    email TIMESTAMP[],
    phone TIMESTAMP[],
    FOREIGN KEY (client) REFERENCES users.accounts (id)
);

CREATE TABLE users.aliases (
    type TEXT NOT NULL,
    target BIGINT NOT NULL,
    id UUID PRIMARY KEY DEFAULT public.uuid_generate_v4()
)

CREATE TABLE users.bots (
    client BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner BIGINT NOT NULL,
    FOREIGN KEY (client) REFERENCES users.accounts (id),
    FOREIGN KEY (owner) REFERENCES users.accounts (id)
);
