CREATE TABLE "channels"."index" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner-id" BIGINT
        NOT NULL,
    "title" TEXT
        NOT NULL
        CONSTRAINT "channels.index-logic-lengthTitle" CHECK (length("title") <= 80),
    "description" TEXT
        CONSTRAINT "channels.index-logic-lengthDescription" CHECK (length("description") <= 350),
    "icon-id" BIGINT,
    "created-at" TIMESTAMP WITHOUT TIME ZONE
        NOT NULL
        DEFAULT TIMEZONE('UTC', now()),
    "is-enabled" BOOLEAN
        NOT NULL
        DEFAULT TRUE,
    "is-public" BOOLEAN
        NOT NULL
        DEFAULT FALSE,
    CONSTRAINT "channels.index-FK-ownerID" FOREIGN KEY ("owner-id") REFERENCES "users"."accounts" ("id"),
    CONSTRAINT "channels.index-FK-iconID" FOREIGN KEY ("icon-id") REFERENCES "files"."index" ("id")
);
