CREATE TABLE channels."index" (
    "id" BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner" BIGINT
        NOT NULL,
    "title" TEXT
        NOT NULL,
    "description" TEXT,
    "icon" BIGINT,
    "created" TIMESTAMP WITHOUT TIME ZONE
        NOT NULL
        DEFAULT TIMEZONE('UTC', now()),
    "enabled" BOOLEAN
        NOT NULL
        DEFAULT TRUE,
    "public" BOOLEAN
        NOT NULL
        DEFAULT FALSE,
    FOREIGN KEY ("owner")
        REFERENCES "users"."accounts" ("id"),
    FOREIGN KEY ("icon")
        REFERENCES "files"."index" ("id"),
    CHECK (length("title") > 2 AND length("title") < 33),
    CHECK (length("description") < 257)
);
